name: tafseer_hafiz_abdusalam
description: Hafiz Abd ul Salam tafseer

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  intl: 0.16.1
  path_provider: 1.6.1
  sqflite: ^1.2.1
  get: ^3.26.0
  flutter_parsed_text: ^1.2.5
  clipboard: ^0.1.2+8
  share: ^0.6.5+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/tafsir.db

  fonts:
    - family: Jameel
      fonts:
        - asset: assets/fonts/jameel.ttf
    - family: NooreHuda
      fonts:
        - asset: assets/fonts/noorehuda.ttf
    - family: Trad
      fonts:
        - asset: assets/fonts/trad.ttf