name: tafseer
description: Hafiz Abdul Salam tafseer

version: 1.2.0+18

publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  auto_size_text: ^3.0.0
  flutter_lints: ^5.0.0
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.4
  fluttertoast: ^8.0.9
  intl: ^0.19.0
  path_provider: ^2.0.9
  sqflite: ^2.0.2
  get: ^4.6.1
  flutter_parsed_text: ^2.2.1
  share_plus: ^6.3.0
  scrollable_positioned_list: ^0.3.1
  visibility_detector: ^0.4.0+2
  hijri: ^3.0.0
  enum_to_string: ^2.0.1
  wakelock: ^0.6.1+2
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.1.6
  upgrader: ^6.0.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_crashlytics: ^4.0.3
  firebase_analytics: ^11.2.0
  path: ^1.8.2
  encrypt: ^5.0.1
  download_assets:
    git:
      url: https://github.com/kodejuice/download_assets.git
      ref: main



dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  win32: ^5.5.4

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/backgrounds/


  fonts:
    - family: Jameel
      fonts:
        - asset: assets/fonts/jameel.ttf
    - family: NooreHuda
      fonts:
        - asset: assets/fonts/noorehuda.ttf
    - family: Trad
      fonts:
        - asset: assets/fonts/trad.ttf
