name: tafseer
description: Hafiz Abdul Salam tafseer

version: 1.0.1+2

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  auto_size_text: ^3.0.0
  flutter_lints: ^1.0.4
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.4
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  path_provider: ^2.0.9
  sqflite: ^2.0.2
  get: ^4.6.1
  flutter_parsed_text: ^2.2.1
  share: ^2.0.4
  scrollable_positioned_list: ^0.2.3
  visibility_detector: ^0.2.2
  hijri: ^3.0.0
  enum_to_string: ^2.0.1
  wakelock: ^0.6.1+2
  download_assets: ^3.0.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.5.3+1
  flutter_native_splash: ^2.1.6
  upgrader: 3.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/backgrounds/


  fonts:
    - family: Jameel
      fonts:
        - asset: assets/fonts/jameel.ttf
    - family: NooreHuda
      fonts:
        - asset: assets/fonts/noorehuda.ttf
    - family: Trad
      fonts:
        - asset: assets/fonts/trad.ttf