name: tafseer_hafiz_abdusalam
description: Hafiz Abd ul Salam tafseer

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1
  flutter_svg: ^0.16.1
  webview_flutter: ^0.3.19+5
  path_provider: 1.6.1
  sqflite: ^1.2.1
  flutter_typeahead: ^1.8.0
  progress_dialog: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/tafsir.db

  fonts:
    - family: Jameel
      fonts:
        - asset: assets/fonts/jameel.ttf

    - family: NooreHuda
      fonts:
        - asset: assets/fonts/noorehuda.ttf